#!/usr/bin/env python

"""
A management script which contains subcommands useful for administration.

It can be invoked from project root with './manage [subcommand]'. For more
information try './manage --help'.

:copyright: (c) 2016 Pinn Technologies, Inc.
:license: All rights reserved
"""

import click
import management as m


@click.group()
def manage():
    pass

# Add subcommands
manage.add_command(m.lint)
manage.add_command(m.shell)
manage.add_command(m.train)

if __name__ == '__main__':
    manage()
